# Generated by Django 6.0.6 on 2026-07-12 14:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0003_savedgrid"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="privacy_agreed_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
