# Generated by Django 6.0.6 on 2026-07-12 14:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0006_alter_user_gender"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="gender",
            field=models.CharField(
                choices=[("F", "여성"), ("M", "남성")], max_length=10
            ),
        ),
    ]
