# Generated by Django 6.0.6 on 2026-07-07 16:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="gender",
            field=models.CharField(
                blank=True, choices=[("M", "남성"), ("F", "여성")], max_length=10
            ),
        ),
    ]
