# Generated by Django 6.0.6 on 2026-07-12 14:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0005_alter_user_gender"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="gender",
            field=models.CharField(
                choices=[("M", "남성"), ("F", "여성")], max_length=10
            ),
        ),
    ]
