# Generated by Django 6.0.3 on 2026-07-10 03:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("grids", "0003_alter_grid_options_grid_bell_count_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="Facility",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "type",
                    models.CharField(
                        choices=[
                            ("cctv", "CCTV"),
                            ("light", "가로등"),
                            ("bell", "비상벨"),
                            ("police", "파출소/지구대"),
                        ],
                        max_length=10,
                    ),
                ),
                ("latitude", models.FloatField()),
                ("longitude", models.FloatField()),
                ("count", models.IntegerField(default=1)),
            ],
            options={
                "indexes": [
                    models.Index(fields=["type"], name="grids_facil_type_50f35e_idx")
                ],
            },
        ),
    ]
