# Generated by Django 6.0.6 on 2026-07-12 13:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("qna", "0002_alter_answer_options_alter_comment_options_and_more"),
    ]

    operations = [
        migrations.DeleteModel(
            name="Comment",
        ),
    ]
