# Generated by Django 6.0.6 on 2026-07-08 06:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("grids", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="grid",
            options={"ordering": ["dong"]},
        ),
    ]
