# Generated by Django 6.0.3 on 2026-07-10 03:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("grids", "0002_alter_grid_options"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="grid",
            options={"ordering": ["dong_group", "dong"]},
        ),
        migrations.AddField(
            model_name="grid",
            name="bell_count",
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name="grid",
            name="boundary_geojson",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="grid",
            name="cctv_count",
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name="grid",
            name="created_at",
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name="grid",
            name="dong_group",
            field=models.CharField(default="", max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="grid",
            name="light_count",
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name="grid",
            name="police_count",
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name="grid",
            name="updated_at",
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name="grid",
            name="dong",
            field=models.CharField(max_length=50, unique=True),
        ),
        migrations.AlterField(
            model_name="grid",
            name="safety_score",
            field=models.FloatField(default=0),
        ),
    ]
