# Generated by Django 6.0.3 on 2026-07-10 04:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("grids", "0004_facility"),
    ]

    operations = [
        migrations.AddField(
            model_name="grid",
            name="is_legal_dong",
            field=models.BooleanField(default=False),
        ),
    ]
