# Generated by Django 6.0.3 on 2026-07-10 04:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("grids", "0005_grid_is_legal_dong"),
    ]

    operations = [
        migrations.AlterField(
            model_name="grid",
            name="dong",
            field=models.CharField(max_length=50),
        ),
        migrations.AddConstraint(
            model_name="grid",
            constraint=models.UniqueConstraint(
                fields=("dong", "is_legal_dong"), name="unique_dong_per_level"
            ),
        ),
    ]
