# Generated by Django 6.0.3 on 2026-07-14 08:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("grids", "0006_alter_grid_dong_grid_unique_dong_per_level"),
    ]

    operations = [
        migrations.AddField(
            model_name="grid",
            name="crime_zone_grade",
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name="grid",
            name="night_safety_grade",
            field=models.FloatField(default=0),
        ),
    ]
