# Generated by Django 6.0.3 on 2026-07-14 09:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("grids", "0007_grid_crime_zone_grade_grid_night_safety_grade"),
    ]

    operations = [
        migrations.CreateModel(
            name="District",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=20, unique=True)),
                ("has_data", models.BooleanField(default=False)),
            ],
            options={
                "ordering": ["name"],
            },
        ),
        migrations.AddField(
            model_name="grid",
            name="gu",
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name="grid",
            name="sido",
            field=models.CharField(blank=True, max_length=20),
        ),
    ]
