# Generated by Django 6.0.6 on 2026-07-16 07:02

from django.db import migrations

def fill_sido_gu(apps, schema_editor):
    Grid = apps.get_model('grids', 'Grid')
    Grid.objects.all().update(sido='서울특별시')
    Grid.objects.filter(dong_group='상계동').update(gu='노원구')
    Grid.objects.filter(dong_group='신림동').update(gu='관악구')

def reverse_fill_sido_gu(apps, schema_editor):
    Grid = apps.get_model('grids', 'Grid')
    Grid.objects.all().update(sido='', gu='')

class Migration(migrations.Migration):

    dependencies = [
        ("grids", "0008_district_grid_gu_grid_sido"),
    ]

    operations = [
        migrations.RunPython(fill_sido_gu, reverse_fill_sido_gu),
    ]
